### ISSUE TITLE
CLASH 订阅转换 RUS 和 AUS 会混进美国节点

### ISSUE THREAD

**Issue by InoryS** [ACL4SSR/ACL4SSR#215]
# 描述

在 [tindy2013/subconverter](https://github.com/tindy2013/subconverter) 中使用  https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/config/ACL4SSR_Online_Full_MultiMode.ini

```
https://api.sublink.dev/sub?target=clash&new_name=true&url=省略&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full_MultiMode.ini&emoji=true&list=false&tfo=true&fdn=false&sort=true&clash.doh=true&new_name=true&append_type=true&udp=true&interval=43200&tls13=true&scv=false

```

节点名为 
```
- name: '[SS] 🇦🇺 AUS 01'
  server: 
  port: 20351
  type: ss
  cipher: aes-128-gcm
  password: 
  plugin: obfs
  plugin-opts:
    mode: http
    host: 
 - name: '[SS] 🇷🇺 RUS 01'
  server: 
  port: 20651
  type: ss
  cipher: aes-128-gcm
  password: 
  plugin: obfs
  plugin-opts:
    mode: http
    host: 
  udp: true
 - name: '[SS] 🇷🇺 RUS 02'
  server: 
  port: 20652
  type: ss
  cipher: aes-128-gcm
  password: 
  plugin: obfs
  plugin-opts:
    mode: http
    host: 
  udp: true
  ```
  时会被分配进美国节点

![image](https://github.com/user-attachments/assets/b1a3604e-0df0-4896-8c46-8d2c3828fdca)
   
# 解决方案
方案 A. 自己 fork 把 ACL4SSR_Online_Full_MultiMode.ini 中的节点正则表达式改一下。

方案 B. 不想改，用 https://github.com/InoryS/Clash-Parser-Online 的 command 功能覆盖节点组，或者删掉错误的节点。

方案 C. 等待本仓库更改。
