### ISSUE TITLE
负载均衡类型问题

### ISSUE THREAD

**Issue by Wyatt323** [ACL4SSR/ACL4SSR#49]
负载均衡有两种类型
一、轮询  strategy: round-robin
二、散列  strategy: consistent-hashing
通过远程配置文件订阅之后默认是散列，我尝试在ini的负载均衡那一行最后加上`round-robin也不生效
请问怎么修改远程配置ini可以实现负载均衡使用轮询

**Comment by juli321-cloud** [comment]
```
parsers:
  - reg: 'slbable$'
    yaml:
      append-proxy-groups:
        - name: ⚖️ 负载均衡-散列
          type: load-balance
          url: 'http://www.google.com/generate_204'
          interval: 300
          strategy: consistent-hashing
        - name: ⚖️ 负载均衡-轮询
          type: load-balance
          url: 'http://www.google.com/generate_204'
          interval: 300
          strategy: round-robin
      commands:
        - proxy-groups.⚖️ 负载均衡-散列.proxies=[]proxyNames
        - proxy-groups.0.proxies.0+⚖️ 负载均衡-散列
        - proxy-groups.⚖️ 负载均衡-轮询.proxies=[]proxyNames
        - proxy-groups.0.proxies.0+⚖️ 负载均衡-轮询
```
