### ISSUE TITLE
Enable UDP and Clash.DoH

### ISSUE THREAD

**Issue by TJT-JTJ** [ACL4SSR/ACL4SSR#584]
![image](https://user-images.githubusercontent.com/63647882/113949034-e0b1a700-9840-11eb-9123-6b9ef51b8bdb.png)
![image](https://user-images.githubusercontent.com/63647882/113949126-18b8ea00-9841-11eb-845d-dc3b312f92ab.png)

Currently the advanced options of 'Enable UDP' and 'Clash.DoH' do not add the required lines to the profile generated: 

```
dns:
  enable: true
  enhanced-mode: fake-ip
  listen: 0.0.0.0:53
  nameserver:
    - [**DoH address**]
  fake-ip-filter:
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
```

Currently the profile only contains the following, along with rules and sub info:
```port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
