### ISSUE TITLE
通过rule-provider方式导入错误

### ISSUE THREAD

**Issue by Android-AwesomeRoy** [ACL4SSR/ACL4SSR#703]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/19187129/154523883-18762d64-226c-4fed-84c8-741d5ba89fb7.png">

config 中写法如下：
``` yaml
  microsoft:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/Microsoft.yaml"
    path: ./ruleset/Microsoft.yaml
    interval: 86400

```
